# Generated by Django 6.0.1 on 2026-03-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/user.png', null=True, upload_to='profile_images/'),
        ),
    ]
