# Generated by Django 6.0.1 on 2026-04-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rank',
            new_name='xp',
        ),
    ]
