# Generated by Django 6.0.1 on 2026-05-02 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_played',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
