# Generated by Django 6.0.1 on 2026-05-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_time_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dnnab4vv0/image/upload/v1780251515/user_khcobv.png', null=True, upload_to='profile_images/'),
        ),
    ]
