# Generated by Django 6.0.1 on 2026-05-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='quizzy/profile_images/user_khcobv.png', null=True, upload_to='profile_images/'),
        ),
    ]
