# Generated by Django 6.0.1 on 2026-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='quizzy/profile_images/user_hir4cn', max_length=500, null=True, upload_to='quizzy/profile_images/'),
        ),
    ]
