# Generated by Django 6.0.1 on 2026-09-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quiz', '0001_initial'),
        ('questions', '0013_category_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuizSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField()),
                ('players_count', models.PositiveIntegerField(default=0)),
                ('first_place_user_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place_summary', to='daily_quiz.userdailyquiz')),
                ('second_place_user_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place_summary', to='daily_quiz.userdailyquiz')),
                ('third_place_user_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place_summary', to='daily_quiz.userdailyquiz')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_daily_quizzes', to='questions.category')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('topic', 'for_date'), name='unique_daily_quiz_summary_per_topic_and_date')],
            },
        ),
    ]
