# Generated by Django 6.0.1 on 2026-09-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quiz', '0002_dailyquizsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquizsummary',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
