# Generated by Django 6.0.1 on 2026-10-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quiz', '0003_alter_dailyquizsummary_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyquiz',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
