# Generated by Django 6.0.1 on 2026-02-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('decision', models.CharField(default='None', max_length=255)),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved')], db_index=True, default='unresolved', max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='questions.question')),
            ],
        ),
    ]
