# Generated by Django 6.0.1 on 2026-02-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questionissues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionissues',
            name='decision',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
