# Generated by Django 6.0.1 on 2026-04-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
