# Generated by Django 6.0.1 on 2026-04-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='info',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
