# Generated by Django 6.0.1 on 2026-04-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_remove_question_difficulty_question_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(db_index=True, default='easy', max_length=10),
        ),
    ]
